# all jokes are taken from "https://v2.jokeapi.dev/" and pyjokes library python
import random
import time
jokes1=[
    "Complaining about the lack of smoking shelters, the nicotine addicted Python programmers said there ought to be 'spaces for tabs'.",
    "Ubuntu users are apt to get this joke.",
    "Obfuscated Reality Mappers (ORMs) can be useful database tools.",
    "Asked to explain Unicode during an interview, Geoff went into detail about his final year university project. He was not hired.",
    "Triumphantly, Beth removed Python 2.7 from her server in 2030. 'Finally!' she said with glee, only to see the announcement for Python 4.4.",
    "An SQL query goes into a bar, walks up to two tables and asks, 'Can I join you?'",
    "When your hammer is C++, everything begins to look like a thumb.",
    "If you put a million monkeys at a million keyboards, one of them will eventually write a Java program. The rest of them will write Perl.",
    "To understand recursion you must first understand recursion.",
    "I suggested holding a 'Python Object Oriented Programming Seminar', but the acronym was unpopular.",
    "'Knock, knock.' 'Who's there?' ... very long pause ... 'Java.'",
    "How many programmers does it take to change a lightbulb? None, that's a hardware problem.",
    "What's the object-oriented way to become wealthy? Inheritance.",
    "Why don't jokes work in octal? Because 7 10 11.",
    "How many programmers does it take to change a lightbulb? None, they just make darkness a standard.",
    "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "Two threads walk into a bar. The barkeeper looks up and yells, 'Hey, I want don't any conditions race like time last!'",
    "Old C programmers don't die, they're just cast into void.",
    "Eight bytes walk into a bar. The bartender asks, 'Can I get you anything?' 'Yeah,' replies the bytes. 'Make us a double.'",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "Why do Java programmers have to wear glasses? Because they don't see sharp.",
    "Software developers like to solve problems. If there are no problems handily available, they will create their own.",
    ".NET was named .NET so that it wouldn't show up in a Unix directory listing.",
    "Hardware: The part of a computer that you can kick.",
    "A programmer was found dead in the shower. Next to their body was a bottle of shampoo with the instructions 'Lather, Rinse and Repeat'.",
    "Optimist: The glass is half full. Pessimist: The glass is half empty. Programmer: The glass is twice as large as necessary.",
    "In C we had to code our own bugs. In C++ we can inherit them.",
    "How come there is no obfuscated Perl contest? Because everyone would win.",
    "If you play a Windows CD backwards, you'll hear satanic chanting ... worse still, if you play it forwards, it installs Windows.",
    "How many programmers does it take to kill a cockroach? Two: one holds, the other installs Windows on it.",
    "What do you call a programmer from Finland? Nerdic.",
    "What did the Java code say to the C code? A: You've got no class.",
    "Why did Microsoft name their search engine BING? Because It's Not Google.",
    "Pirates go 'arg!', computer pirates go 'argv!'",
    "Software salesmen and used-car salesmen differ in that the latter know when they are lying.",
    "Child: Dad, why does the sun rise in the east and set in the west? Dad: Son, it's working, don't touch it.",
    "Why do programmers confuse Halloween with Christmas? Because OCT 31 == DEC 25.",
    "How many Prolog programmers does it take to change a lightbulb? false.",
    "Real programmers can write assembly code in any language.",
    "Waiter: Would you like coffee or tea? Programmer: Yes.",
    "What do you get when you cross a cat and a dog? Cat dog sin theta.",
    "If loving you is ROM I don't wanna read write.",
    "A programmer walks into a foo...",
    "A programmer walks into a bar and orders 1.38 root beers. The bartender informs her it's a root beer float. She says 'Make it a double!'",
    "What is Benoit B. Mandelbrot's middle name? Benoit B. Mandelbrot.",
    "Why are you always smiling? That's just my... regular expression.",
    "ASCII stupid question, get a stupid ANSI.",
    "A programmer had a problem. He thought to himself, 'I know, I'll solve it with threads!'. has Now problems. two he",
    "Why do sin and tan work? Just cos.",
    "Java: Write once, run away.",
    "I would tell you a joke about UDP, but you would never get it.",
    "A QA engineer walks into a bar. Runs into a bar. Crawls into a bar. Dances into a bar. Tiptoes into a bar. Rams a bar. Jumps into a bar.",
    "My friend's in a band called '1023 Megabytes'... They haven't got a gig yet!",
    "I had a problem so I thought I'd use Java. Now I have a ProblemFactory.",
    "QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.",
    "A product manager walks into a bar, asks for drink. Bartender says no, but will consider adding later.",
    "How do you generate a random string? Put a first year Computer Science student in Vim and ask them to save and exit.",
    "I've been using Vim for a long time now, mainly because I can't figure out how to exit.",
    "How do you know whether a person is a Vim user? Don't worry, they'll tell you.",
    "Waiter: He's choking! Is anyone a doctor? Programmer: I'm a Vim user.",
    "3 Database Admins walked into a NoSQL bar. A little while later they walked out because they couldn't find a table.",
    "How to explain the movie Inception to a programmer? When you run a VM inside another VM, inside another VM ... everything runs real slow!",
    "What do you call a parrot that says \"Squawk! Pieces of nine! Pieces of nine!\"? A parrot-ey error.",
    "There are only two hard problems in Computer Science: cache invalidation, naming things and off-by-one-errors.",
    "There are 10 types of people: those who understand binary and those who don't.",
    "There are 2 types of people: those who can extrapolate from incomplete data sets...",
    "There are II types of people: Those who understand Roman Numerals and those who don't.",
    "There are 10 types of people: those who understand hexadecimal and 15 others.",
    "There are 10 types of people: those who understand binary, those who don't, and those who were expecting this joke to be in trinary.",
    "There are 10 types of people: those who understand trinary, those who don't, and those who have never heard of it.",
    "What do you call eight hobbits? A hobbyte.",
    "The best thing about a Boolean is even if you are wrong, you are only off by a bit.",
    "A good programmer is someone who always looks both ways before crossing a one-way street.",
    "There are two ways to write error-free programs; only the third one works.",
    "QAs consist of 55% water, 30% blood and 15% Jira tickets.",
    "Sympathy for the Devil is really just about being nice to QAs.",
    "How many QAs does it take to change a lightbulb? They noticed that the room was dark. They don't fix problems, they find them.",
    "A programmer crashes a car at the bottom of a hill, a bystander asks what happened, he says \"No idea. Let's push it back up and try again\".",
    "What do you mean 911 is only for emergencies? I've got a merge conflict.",
    "Writing PHP is like peeing in the swimming pool, everyone did it, but we don't need to bring it up in public.",
    "Why did the QA cross the road? To ruin everyone's day.",
    "Number of days since I have encountered an array index error: -1.",
    "Number of days since I have encountered an off-by-one error: 0.",
    "Speed dating is useless. 5 minutes is not enough to properly explain the benefits of the Unix philosophy.",
    "Microsoft hold a bi-monthly internal \"productive week\" where they use Google instead of Bing.",
    "Schrodinger's attitude to web development: If I don't look at it in Internet Explorer then there's a chance it looks fine.",
    "Finding a good PHP developer is like looking for a needle in a haystack. Or is it a hackstack in a needle?",
    "Unix is user friendly. It's just very particular about who its friends are.",
    "A COBOL programmer makes millions with Y2K remediation and decides to get cryogenically frozen. \"The year is 9999. You know COBOL, right?\"",
    "The C language combines all the power of assembly language with all the ease-of-use of assembly language.",
    "An SEO expert walks into a bar, bars, pub, public house, Irish pub, tavern, bartender, beer, liquor, wine, alcohol, spirits...",
    "What does 'Emacs' stand for? 'Exclusively used by middle aged computer scientists.'",
    "What does pyjokes have in common with Adobe Flash? It gets updated all the time, but never gets any better.",
    "Why does Waldo only wear stripes? Because he doesn't want to be spotted.",
    "I went to a street where the houses were numbered 8k, 16k, 32k, 64k, 128k, 256k and 512k. It was a trip down Memory Lane.",
    "!false, (It's funny because it's true)",
    "['hip', 'hip'] (hip hip array!)",
    "When Chuck Norris throws exceptions, it's across the room.",
    "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds.",
    "Chuck Norris doesn't have disk latency because the hard drive knows to hurry the hell up, or else.",
    "Chuck Norris writes code that optimises itself.",
    "Chuck Norris can't test for equality because he has no equal.",
    "Chuck Norris doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick().",
    "Chuck Norris's first program was kill -9.",
    "Chuck Norris burst the dot com bubble.",
    "All browsers support the hex definitions #chuck and #norris for the colours black and blue.",
    "MySpace isn't really your space, it's Chuck's (he just lets you use it).",
    "Chuck Norris can write infinitely recursive functions and have them return.",
    "Chuck Norris can solve the Towers of Hanoi in one move.",
    "The only design pattern Chuck Norris knows is the God Object Pattern.",
    "Chuck Norris finished World of Warcraft.",
    "Project managers never ask Chuck Norris for estimations.",
    "Chuck Norris doesn't use web standards as the web will conform to him.",
    "'It works on my machine' always holds true for Chuck Norris.",
    "Chuck Norris doesn't do Burn Down charts, he does Smack Down charts.",
    "Chuck Norris can delete the Recycling Bin.",
    "Chuck Norris's beard can type 140 words per minute.",
    "Chuck Norris can unit test entire applications with a single assertion, 'it works'.",
    "Chuck Norris doesn't bug hunt as that signifies a probability of failure, he goes bug killing.",
    "Chuck Norris's keyboard doesn't have a Ctrl key because nothing controls Chuck Norris.",
    "Chuck Norris can overflow your stack just by looking at it.",
    "To Chuck Norris, everything contains a vulnerability.",
    "Chuck Norris doesn't sudo, the shell just knows it's him and does what it's told.",
    "Chuck Norris doesn't need a debugger, he just stares at the code until it confesses.",
    "Chuck Norris can access private methods.",
    "Chuck Norris can instantiate an abstract class.",
    "Chuck Norris does not need to know about Class Factory Pattern. He can instantiate interfaces.",
    "The class object inherits from Chuck Norris.",
    "For Chuck Norris, NP-Hard = O(1).",
    "Chuck Norris knows the last digit of Pi.",
    "Chuck Norris's Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.",
    "Chuck Norris solved the Travelling Salesman problem in O(1) time: break salesman into N pieces; kick each piece to a different city.",
    "No statement can catch the ChuckNorrisException.",
    "Chuck Norris doesn't pair program.",
    "Chuck Norris can write multi-threaded applications with a single thread.",
    "Chuck Norris doesn't need to use AJAX because pages are too afraid to postback anyways.",
    "Chuck Norris doesn't use reflection, reflection asks politely for his help.",
    "There is no Esc key on Chuck Norris' keyboard, because no one escapes Chuck Norris.",
    "Chuck Norris can binary search unsorted data.",
    "Chuck Norris doesn't needs try-catch, exceptions are too afraid to raise.",
    "Chuck Norris went out of an infinite loop.",
    "If Chuck Norris writes code with bugs, the bugs fix themselves.",
    "Chuck Norris hosting is 101% uptime guaranteed.",
    "Chuck Norris's keyboard has the Any key.",
    "Chuck Norris can access the database from the UI.",
    "Chuck Norris's programs never exit, they are terminated.",
    "Chuck Norris insists on strongly-typed programming languages.",
    "The Chuck Norris protocol design method has no status, requests or responses, only commands.",
    "Chuck Norris's programs occupy 150% of CPU, even when they are not running.",
    "Chuck Norris can spawn threads that complete before they are started.",
    "Chuck Norris's programs do not accept input.",
    "Chuck Norris can install iTunes without installing Quicktime.",
    "Chuck Norris doesn't need an OS.",
    "Chuck Norris's OSI network model has only one layer - Physical.",
    "Chuck Norris can compile syntax errors.",
    "Every SQL statement that Chuck Norris codes has an implicit 'COMMIT' in its end.",
    "Chuck Norris does not need to type-cast. The Chuck-Norris Compiler (CNC) sees through things. All the way down. Always.",
    "Chuck Norris does not code in cycles, he codes in strikes.",
    "Chuck Norris compresses his files by doing a flying round house kick to the hard drive.",
    "Chick Norris solved the halting problem.",
    "With Chuck Norris P = NP. There's no nondeterminism with Chuck Norris decisions.",
    "Chuck Norris can retrieve anything from /dev/null.",
    "No one has ever pair-programmed with Chuck Norris and lived to tell the tale.",
    "No one has ever spoken during review of Chuck Norris' code and lived to tell the tale.",
    "Chuck Norris doesn't use a GUI, he prefers COMMAND line.",
    "Chuck Norris doesn't use Oracle, he is the Oracle.",
    "Chuck Norris can dereference NULL.",
    "A diff between your code and Chuck Norris's is infinite.",
    "The Chuck Norris Eclipse plugin made alien contact.",
    "Chuck Norris is the ultimate mutex, all threads fear him.",
    "Don't worry about tests, Chuck Norris's test cases cover your code too.",
    "Each hair in Chuck Norris's beard contributes to make the world's largest DDOS.",
    "Chuck Norris's log statements are always at the FATAL level.",
    "Chuck Norris's database has only one table, 'Kick', which he drops frequently.",
    "Chuck Norris completed World of Warcraft.",
    "When Chuck Norris breaks the build, you can't fix it, because there is not a single line of code left.",
    "Chuck Norris types with one finger. He points it at the keyboard and the keyboard does the rest.",
    "Chuck Norris's programs can pass the Turing Test by staring at the interrogator.",
    "If you try to kill -9 Chuck Norris's programs, it backfires.",
    "Chuck Norris performs infinite loops in under 4 seconds.",
    "Chuck Norris can overwrite a locked variable.",
    "Chuck Norris knows the value of NULL, and he can sort by it too.",
    "Chuck Norris can install a 64-bit operating system on 32-bit machines.",
    "Chuck Norris can write to an output stream.",
    "Chuck Norris can read from an input stream.",
    "Chuck Norris never has to build his program to machine code. Machines have learnt to interpret Chuck Norris's code.",
    "Chuck Norris's unit tests don't run. They die.",
    "Chuck Norris causes the Blue Screen of Death.",
    "Chuck Norris can make a class that is both abstract and final.",
    "Chuck Norris could use anything in java.util.* to kill you, including the javadocs.",
    "Code runs faster when Chuck Norris watches it.",
    "Chuck Norris doesn't use REST, he waits.",
    "Everyone likes Chuck Norris on Facebook, whether they choose to or not.",
    "You can't follow Chuck Norris on Twitter, because he follows you.",
    "Chuck Norris's calculator has only 3 keys: 0, 1, and NAND.",
    "Chuck Norris only uses global variables. He has nothing to hide.",
    "Chuck Norris once implemented an HTTP server in a single printf call. It is now the heart of Apache webserver.",
    "Chuck Norris writes directly in binary. He then writes the source code as documentation for other programmers.",
    "Chuck Norris once shifted a bit so hard, it ended up on a different computer.",
    "Q: What is Chuck Norris's favorite Javascript framework? A: Knockout.js.",
    'Doctor: "I have some news about your baby."\nParents: "Don\'t tell us the gender, we want to keep it a surprise."\nDoctor: "Oh I get it, you\'re those type of people. Okay, well IT is not breathing."', "If you're here for the yodeling lesson, please form an orderly orderly orderly queue.", "I'm reading a book about anti-gravity. It's impossible to put down!", 'My wife and I have reached the difficult decision that we do not want children.\nIf anybody does, please just send me your contact details and we can drop them off tomorrow.', "Algorithm: A word used by programmers when they don't want to explain how their code works.", 'Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.', 'UDP is better in the COVID era since it avoids unnecessary handshakes.', 'The glass is neither half-full nor half-empty, the glass is twice as big as it needs to be.', 'I was reading a great book about an immortal dog the other day. It was impossible to put down.', "Two reasons I don't give money to homeless people.\n1) They are going to spend it all on drugs and alcohol\n2) I am going to spend it all on drugs and alcohol.", "SchrÃ¶dinger's cat walks into a bar and doesn't.", 'Today, my son asked "Can I have a book mark?" and I burst into tears.\n11 years old and he still doesn\'t know my name is Brian.', "The six stages of debugging:\n1. That can't happen.\n2. That doesn't happen on my machine.\n3. That shouldn't happen.\n4. Why does that happen?\n5. Oh, I see.\n6. How did that ever work?", "Knock knock.\nWho's there?\nRecursion.\nRecursion who?\nKnock knock.", 'Oysters hate to give away their pearls because they are shellfish.', 'I was struggling to figure out how lightning works, but then it struck me.', 'My wife is really mad at the fact that I have no sense of direction.\nSo I packed up my stuff and right.', "My ex had an accident. I told the paramedics the wrong blood type for her. She'll finally experience what rejection is really like.", 'A horse walks into a bar.\n"Hey", the Bartender says.\n"Sure", the horse replies.', 'I have these weird muscle spasms in my gluteus maximus.\nI figured out from my doctor that everything was alright:\nHe said "Weird flex, butt okay."', 'To whoever stole my copy of Microsoft Office, I will find you. You have my Word!', 'Eight bytes walk into a bar.\nThe bartender asks, "Can I get you anything?"\n"Yeah," reply the bytes.\n"Make us a double."', "Hey Girl,\nRoses are #ff0000,\nViolets are #0000ff,\nI use hex codes,\nBut I'd use RGB for you.", 'Four engineers get into a car. The car won\'t start.\nThe Mechanical engineer says "It\'s a broken starter".\nThe Electrical engineer says "Dead battery".\nThe Chemical engineer says "Impurities in the gasoline".\nThe IT engineer says "Hey guys, I have an idea: How about we all get out of the car and get back in".', "I didn't vaccinate my 10 kids and the one that survived is fine!", "Never date a baker. They're too kneady.", 'Today I learned that changing random stuff until your program works is "hacky" and a "bad coding practice" but if you do it fast enough it\'s "Machine Learning" and pays 4x your current salary.', "I bought some shoes from a drug dealer. I don't know what he laced them with, but I was tripping all day!", 'Debugging: Removing the needles from the haystack.', "Debugging is like being the detective in a crime movie where you're also the murderer at the same time.", 'A byte walks into a bar looking miserable.\nThe bartender asks it: "What\'s wrong buddy?"\n"Parity error." it replies. \n"Ah that makes sense, I thought you looked a bit off."', 'Two SQL tables sit at the bar. A query approaches and asks "Can I join you?"', "How do you tell HTML from HTML5?\n- Try it out in Internet Explorer\n- Did it work?\n- No?\n- It's HTML5.", '"Knock, knock."\n"Who\'s there?"\n\n[very long pause]\n\n"Java."', 'A neutron walks into a bar and asks for a price on a drink.\nThe barkeeper says: "For you... no charge!"', '"Honey, go to the store and buy some eggs."\n"OK."\n"Oh and while you\'re there, get some milk."\nHe never returned.', 'I have a fish that can breakdance! Only for 20 seconds though, and only once.', "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.", 'My little daughter came to me all excited, saying "Daddy! Daddy! Guess how old I\'ll be in June!"\n"Oh I don\'t know princess, why don\'t you tell me?" I said. She gave me a huge smile and held up four fingers.\nIt\'s now three hours later, police have joined in and she still won\'t say where she got them.', "There are only 10 kinds of people in this world: those who know binary and those who don't.", 'Java and C were telling jokes. It was C\'s turn, so he writes something on the wall, points to it and says "Do you get the reference?" But Java didn\'t.', 'Two C strings walk into a bar.\nThe bartender asks "What can I get ya?"\nThe first string says "I\'ll have a gin and tonic."\nThe second string thinks for a minute, then says "I\'ll take a tequila sunriseJF()#$JF(#)$(@J#()$@#())!*FNIN!OBN134ufh1ui34hf9813f8h8384h981h3984h5F!##@"\nThe first string apologizes, "You\'ll have to excuse my friend, he\'s not null-terminated."', 'A guy walks into a bar and asks for 1.4 root beers.\nThe bartender says "I\'ll have to charge you extra, that\'s a root beer float".\nThe guy says "In that case, better make it a double."', 'Two fish in a tank. One turns to the other and says, "Do you know how to drive this thing?"', "A programmer puts two glasses on his bedside table before going to sleep.\nA full one, in case he gets thirsty, and an empty one, in case he doesn't.", 'My husband and I were happy for 20 years. And then we met.', 'I have a joke about trickle down economics, but 99% of you will never get it.', 'Judge: "I sentence you to the maximum punishment..."\nMe (thinking): "Please be death, please be death..."\nJudge: "Learn Java!"\nMe: "Damn."', 'My parents raised me as an only child, which really annoyed my younger brother.', 'Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.', 'Have a great weekend!\nI hope your code behaves the same on Monday as it did on Friday.', 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."', 'ASCII silly question, get a silly ANSI.', '"We messed up the keming again guys."', '"Can I tell you a TCP joke?"\n"Please tell me a TCP joke."\n"OK, I\'ll tell you a TCP joke."', 'I\'ll never forget my Granddad\'s last words to me just before he died. "Are you still holding the ladder?"', 'A SQL statement walks into a bar and sees two tables.\nIt approaches, and asks "may I join you?"', "// This line doesn't actually do anything, but the code stops working when I delete it.", "My grandfather says I'm too reliant on technology.\nI called him a hypocrite and unplugged his life support.", 'A perfectionist walked into a bar... apparently, the bar was not set high enough.', "I have a joke about Stack Overflow, but you would say it's a duplicate.", 'If Bill Gates had a dime for every time Windows crashed ... Oh wait, he does.', "Relationship Status: just tried to reach for my dog's paw and he pulled it away so I pretended I was reaching for the remote.", "I've got a really good UDP joke to tell you but I donâ\x80\x99t know if you'll get it.", 'The generation of random numbers is too important to be left to chance.', 'My girlfriend\'s dog died, so I tried to cheer her up by getting her an identical one. It just made her more upset. She screamed at me, "What am I supposed to do with two dead dogs?"', '"How do you tell HTML from HTML5?\\n- Try it out in Internet Explorer\\n- Did it work?\\n- No?\\n- It\'s HTML5."', '"The six stages of debugging:\\n1. That can\'t happen.\\n2. That doesn\'t happen on my machine.\\n3. That shouldn\'t happen.\\n4. Why does that happen?\\n5. Oh, I see.\\n6. How did that ever work?"', '\'"Honey, go to the store and buy some eggs."\\n"OK."\\n"Oh and while you\\\'re there, get some milk."\\nHe never returned.\'', "'I have a fish that can breakdance! Only for 20 seconds though, and only once.'", '\'Today, my son asked "Can I have a book mark?" and I burst into tears.\\n11 years old and he still doesn\\\'t know my name is Brian.\'', '"I\'m reading a book about anti-gravity. It\'s impossible to put down!"', '"I didn\'t vaccinate my 10 kids and the one that survived is fine!"', '"My ex had an accident. I told the paramedics the wrong blood type for her. She\'ll finally experience what rejection is really like."', '"Relationship Status: just tried to reach for my dog\'s paw and he pulled it away so I pretended I was reaching for the remote."', '"Debugging is like being the detective in a crime movie where you\'re also the murderer at the same time."', '\'I have these weird muscle spasms in my gluteus maximus.\\nI figured out from my doctor that everything was alright:\\nHe said "Weird flex, butt okay."\'', "'The glass is neither half-full nor half-empty, the glass is twice as big as it needs to be.'", '\'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\\\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\\\'t worry about warnings; we only worry about errors."\'', "'I was reading a great book about an immortal dog the other day. It was impossible to put down.'", '\'Eight bytes walk into a bar.\\nThe bartender asks, "Can I get you anything?"\\n"Yeah," reply the bytes.\\n"Make us a double."\'', '"My grandfather says I\'m too reliant on technology.\\nI called him a hypocrite and unplugged his life support."', '\'A horse walks into a bar.\\n"Hey", the Bartender says.\\n"Sure", the horse replies.\'', '\'My little daughter came to me all excited, saying "Daddy! Daddy! Guess how old I\\\'ll be in June!"\\n"Oh I don\\\'t know princess, why don\\\'t you tell me?" I said. She gave me a huge smile and held up four fingers.\\nIt\\\'s now three hours later, police have joined in and she still won\\\'t say where she got them.\'', "'My husband and I were happy for 20 years. And then we met.'", '"Java is like Alzheimer\'s, it starts off slow, but eventually, your memory is gone."', '\'A guy walks into a bar and asks for 1.4 root beers.\\nThe bartender says "I\\\'ll have to charge you extra, that\\\'s a root beer float".\\nThe guy says "In that case, better make it a double."\'', '"Never date a baker. They\'re too kneady."', '"A programmer puts two glasses on his bedside table before going to sleep.\\nA full one, in case he gets thirsty, and an empty one, in case he doesn\'t."', '\'"Can I tell you a TCP joke?"\\n"Please tell me a TCP joke."\\n"OK, I\\\'ll tell you a TCP joke."\'', "'ASCII silly question, get a silly ANSI.'", "'A perfectionist walked into a bar... apparently, the bar was not set high enough.'", '"Knock knock.\\nWho\'s there?\\nRecursion.\\nRecursion who?\\nKnock knock."', "'Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.'", '\'A SQL statement walks into a bar and sees two tables.\\nIt approaches, and asks "may I join you?"\'', '\'I\\\'ll never forget my Granddad\\\'s last words to me just before he died. "Are you still holding the ladder?"\'', '"Schr\\xc3\\xb6dinger\'s cat walks into a bar and doesn\'t."', '"Two reasons I don\'t give money to homeless people.\\n1) They are going to spend it all on drugs and alcohol\\n2) I am going to spend it all on drugs and alcohol."', '"// This line doesn\'t actually do anything, but the code stops working when I delete it."', "'Have a great weekend!\\nI hope your code behaves the same on Monday as it did on Friday.'", '\'Two fish in a tank. One turns to the other and says, "Do you know how to drive this thing?"\'', '\'A neutron walks into a bar and asks for a price on a drink.\\nThe barkeeper says: "For you... no charge!"\'', "'My parents raised me as an only child, which really annoyed my younger brother.'", "'UDP is better in the COVID era since it avoids unnecessary handshakes.'", '"Algorithm: A word used by programmers when they don\'t want to explain how their code works."', "'Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.'", '"I\'ve got a really good UDP joke to tell you but I don\\xe2\\x80\\x99t know if you\'ll get it."', "'Debugging: Removing the needles from the haystack.'", "'To whoever stole my copy of Microsoft Office, I will find you. You have my Word!'", '"I bought some shoes from a drug dealer. I don\'t know what he laced them with, but I was tripping all day!"', '\'"We messed up the keming again guys."\'', "'If Bill Gates had a dime for every time Windows crashed ... Oh wait, he does.'", '\'Doctor: "I have some news about your baby."\\nParents: "Don\\\'t tell us the gender, we want to keep it a surprise."\\nDoctor: "Oh I get it, you\\\'re those type of people. Okay, well IT is not breathing."\'', "'I have a joke about trickle down economics, but 99% of you will never get it.'", '"Hey Girl,\\nRoses are #ff0000,\\nViolets are #0000ff,\\nI use hex codes,\\nBut I\'d use RGB for you."', '"I have a joke about Stack Overflow, but you would say it\'s a duplicate."', "'The generation of random numbers is too important to be left to chance.'", '\'Two C strings walk into a bar.\\nThe bartender asks "What can I get ya?"\\nThe first string says "I\\\'ll have a gin and tonic."\\nThe second string thinks for a minute, then says "I\\\'ll take a tequila sunriseJF()#$JF(#)$(@J#()$@#())!*FNIN!OBN134ufh1ui34hf9813f8h8384h981h3984h5F!##@"\\nThe first string apologizes, "You\\\'ll have to excuse my friend, he\\\'s not null-terminated."\'', '\'Two SQL tables sit at the bar. A query approaches and asks "Can I join you?"\'', "'Oysters hate to give away their pearls because they are shellfish.'", '"There are only 10 kinds of people in this world: those who know binary and those who don\'t."', '"If you\'re here for the yodeling lesson, please form an orderly orderly orderly queue."', "'I was struggling to figure out how lightning works, but then it struck me.'", "'My wife and I have reached the difficult decision that we do not want children.\\nIf anybody does, please just send me your contact details and we can drop them off tomorrow.'", '\'My girlfriend\\\'s dog died, so I tried to cheer her up by getting her an identical one. It just made her more upset. She screamed at me, "What am I supposed to do with two dead dogs?"\'', '\'Judge: "I sentence you to the maximum punishment..."\\nMe (thinking): "Please be death, please be death..."\\nJudge: "Learn Java!"\\nMe: "Damn."\'', '\'Java and C were telling jokes. It was C\\\'s turn, so he writes something on the wall, points to it and says "Do you get the reference?" But Java didn\\\'t.\'', '\'Today I learned that changing random stuff until your program works is "hacky" and a "bad coding practice" but if you do it fast enough it\\\'s "Machine Learning" and pays 4x your current salary.\'', '\'A byte walks into a bar looking miserable.\\nThe bartender asks it: "What\\\'s wrong buddy?"\\n"Parity error." it replies. \\n"Ah that makes sense, I thought you looked a bit off."\'', '\'"Knock, knock."\\n"Who\\\'s there?"\\n\\n[very long pause]\\n\\n"Java."\'', '\'Four engineers get into a car. The car won\\\'t start.\\nThe Mechanical engineer says "It\\\'s a broken starter".\\nThe Electrical engineer says "Dead battery".\\nThe Chemical engineer says "Impurities in the gasoline".\\nThe IT engineer says "Hey guys, I have an idea: How about we all get out of the car and get back in".\'', "'My wife is really mad at the fact that I have no sense of direction.\\nSo I packed up my stuff and right.'"]
jokes2=['Jokes about anti-vaxxer parents never get old.////Just like their kids.','What do you get if you lock a monkey in a room with a typewriter for 8 hours?////A regular expression.','Why couldn\'t the skeleton go to the Christmas party?////Because he had no body to go with!','Why did the JavaScript heap close shop?////It ran out of memory.','What do you call a witch at the beach?////A Sandwich.','What do you call a group of 8 Hobbits?////A Hobbyte.','What is the most used language in programming?////Profanity.','Dads are like boomerangs.////I hope.','What says Oh Oh Oh?////Santa walking backwards!','A grocery store cashier asked if I would like my milk in a bag.////I told her "No, thanks. The carton works fine".','Why did the Python data scientist get arrested at customs?////She was caught trying to import pandas!','What do Asian people call fingers?////Limb Limbs.','A Roman walks into a bar and raises 2 fingers and says to the bartender...////"Five beers, please."','You see, mountains aren\'t just funny.////They are hill areas.','The past, the present and the future walk into a bar.////It was tense.','Why do ghosts go on diets?////So they can keep their ghoulish figures.','The other day my wife asked me to pass her lipstick, but I accidentally gave her a glue stick.////She still isn\'t talking to me.','How much did your chimney cost?////Nothing, it was on the house.','I just saw my wife trip over and drop a basket full of ironed clothes.////I watched it all unfold.','What\'s the best thing about Switzerland?////I don\'t know, but the flag is a big plus.','Why was the JavaScript developer sad?////Because he didn\'t Node how to Express himself!','What time did the man go to the dentist?////Tooth hurt-y.','Why is 6 afraid of 7 in hexadecimal Canada?////Because 7 8 9 A?','Hey, wanna hear a joke?////Parsing HTML with regex.','Why was the mushroom always invited to parties?////Cause he\'s a fungi.','Two peanuts were walking.////One was assaulted.','A web developer walks into a restaurant.////He immediately leaves in disgust as the restaurant was laid out in tables.','My wife left me because I\'m too insecure and paranoid.////Oh wait, never mind. She was just getting the mail.','I asked my wife if I was the only one she\'s been with.////She said, "Yes, the others were at least sevens or eights."','What is the best prefix for global variables?//////','Did you hear about the cheese factory that exploded in France?////There was nothing but de brie.','How do you generate a random string?////Put a Windows user in front of Vim and tell him to exit.','Why are modern programming languages so materialistic?////Because they are object-oriented.','Why did the chicken cross the road, roll in the mud and cross the road again?////He was a dirty double-crosser!','Why are cats so good at video games?////They have nine lives.','Why does the size of the snack not matter to a giraffe?////Because even a little bit goes a long way.','No matter how kind you are...////German kids are always Kinder.','I WRITE MY JOKES IN CAPITALS.////THIS ONE WAS WRITTEN IN PARIS.','What does a turkey dress up as for Halloween?////A gobblin\'!','How do construction workers party?////They raise the roof.','I can\'t believe I got fired from the calendar factory.////All I did was take a day off.','What\'s the difference between a poorly dressed man on a unicycle and a well dressed man on a bicycle?////Attire.','I told my psychiatrist I got suicidal tendencies.////He said from now on I have to pay in advance.','Why can\'t orphans play baseball?////They don\'t know where home is.','Why shouldn\'t you visit an expensive wig shop?////It\'s too high a price "toupee."','Why does Santa have three gardens?////So he can \'ho ho ho\'!','I\'m thinking of setting up a comedy group to help people going through cancer treatment.////I\'ll call it "A Sense of Tumor".','Why was the river rich?////Because it had two banks.','Why does Santa go down the chimney?////Because it soots him!','What do you call 4 Mexicans in quicksand?////Quatro Sinko.','I used to love to tell dad jokes.////Dad, come back...','What is a dying programmer\'s last program?////Goodbye, world!','My wife divorced me so I stole her wheelchair.////Guess who came crawling back.','Who hides in the bakery at Christmas?////A mince spy!','How did the programmer die in the shower?////He read the shampoo bottle instructions: Lather. Rinse. Repeat.','What did the customer say to the waiter?////I\'m all fed up with your service.','Why do programmers prefer using the dark mode?////Because light attracts bugs.','Did you hear about the claustrophobic astronaut?////He just needed a little space.','I walked into a bar once.////It really hurt my head.','why do python programmers wear glasses?////Because they can\'t C.','What\'s Santa\'s favourite type of music?////Wrap!','Dark humor is like cancer.////It\'s more funny when children get it.','I hate Russian matryoshka dolls.////They\'re so full of themselves.','What did the cell say when his sister cell stepped on his foot?////Mitosis.','Why do programmers confuse Halloween and Christmas?////Because Oct 31 = Dec 25','My neighbor is a 90 year old with Alzheimer\'s, I see him every morning and he asks me If I\'ve seen his wife.\nEvery day I have to tell this poor man that his wife died 20 years ago.\nI could have moved to another house or even ignore his question.////But the look of joy in his eyes whenever I answer him is worth the world.','What kind of motorbike does Santa ride?////A Holly Davidson!','This morning I accidentally made my coffee with Red Bull instead of water.////I was already on the highway when I noticed I forgot my car at home.','Why is Linux safe?////Hackers peak through Windows only.','Why did the ghost go inside the bar?////For the boos.','Why did the banana go see a doctor?////Because it wasn\'t peeling well.','Why do Java programmers hate communism?////They don\'t want to live in a classless society.','What\'s black and sits at the top of a stairwell?////A paraplegic after a house fire.','What do Santa\'s little helpers learn at school?////The elf-abet!\n','How many programmers does it take to screw in a light bulb?////None. It\'s a hardware problem.','Why did the functional programmer get thrown out of school?////Because he refused to take classes.','Two guys walked into a bar.////The third guy ducked.','To prove he was right, the flat-earther walked to the end of the Earth.////He eventually came around.','Why did the programmer quit his job?////Because he didn\'t get arrays.','What do you call a pile of kittens?////A meowntain.','Mom asked me where I\'m taking her to go out to eat for mother\'s day.////I told her, "We already have food in the house".','I stayed up all night wondering where the sun went.////Then it dawned on me.','Why do programmers wear glasses?////Because they need to C#','Why does no one like SQLrillex?////He keeps dropping the database.','What does the mermaid wear to math class?////Algae-bra.','"99.9% of the people are dumb!"////"Fortunately I belong to the remaining 1%"','Why are Assembly programmers always soaking wet?////They work below C-level.','Who is Santa\'s favourite singer?////Elf-is Presley!','How did Harry Potter get down the hill?////Walking...\nJK, Rolling.','I had a granny that we couldn\'t decide whether to bury or cremate////In the end we decided to just let her live.','Why do cows wear bells?////Because their horns don\'t work!','I was feeling depressed, my wife put her hand on my back and said "Earth."////It meant the world to me.','What do you call a developer who doesn\'t comment code?////A developer.','What is the least spoken language in the world?////Sign language.','What kind of car did Whitney Houston drive?////A Hyundaiiiiiiiiiiii','Why didn\'t the skeleton go for prom?////Because it had nobody.','What do you call a kid with no arms and an eyepatch?////Names.','Why did Santa\'s helper see the doctor?////Because he had a low "elf" esteem!','So I made a graph of all my past relationships.////It has an ex axis and a why axis.','What does Santa suffer from if he gets stuck in a chimney?////Claustrophobia!','What\'s it like to be kissed by a vampire?////It\'s a pain in the neck.','Why did the programmer jump on the table?////Because debug was on his screen.','Why do front end developers eat lunch alone?////Because they don\'t know how to join tables.','Which is faster, Hot or cold?////Hot, because you can catch a cold','Thank you student loans for getting me through college.////I don\'t think I\'ll ever be able to repay you.','My mother said, "You won\'t amount to anything because you always procrastinate."////I said, "Oh yeah... Just you wait."','When I was a kid, I made a really big sandcastle with my grandma.////Unfortunately, that didn\'t impress anyone at the cremation...','What did the boy with no arms get for Christmas?////I don\'t know, he hasn\'t opened it yet.','What\'s the difference between an in-law and an outlaw?////An outlaw is wanted.','Whats the Grinchs least favorite band?////The Who.','What is in a ghost\'s nose?////Boo-gers.','Hey baby I wish your name was asynchronous...////... so you\'d give me a callback.','What do elves post on Social Media?////Elf-ies!','Why do they call it hyper terminal?////Too much Java.','What\'s the object-oriented way to become wealthy?////Inheritance.','What kind of doctor is Dr. Pepper?////He\'s a fizzician.','Which part of the hospital has the least privacy?////The ICU.','So what\'s a set of predefined steps the government might take to preserve the environment?////An Al-Gore-ithm.','What do you call a deer with no eyes?////No eye deer.','How can you tell an extroverted programmer?////He looks at YOUR shoes when he\'s talking.','Why did the database administrator leave his wife?////She had one-to-many relationships.','Why did the koala get rejected?////Because he did not have any koalafication.','How did you make your friend rage?////I implemented a greek question mark in his JavaScript code.','I just got fired from my job at the keyboard factory.////They told me I wasn\'t putting in enough shifts.','Why did the Romanian stop reading?////They wanted to give the Bucharest.','What do you call a cow with no legs?////Ground beef.','My employer came running to me and said, "I was looking for you all day! Where the hell have you been?"////I replied, "Good employees are hard to find."','The gas Argon walks into a bar.\nThe barkeeper says "What would you like to drink?"////But Argon doesn\'t react.','Why did the Python programmer not respond to the foreign mails he got?////Because his interpreter was busy collecting garbage.','What\'s the difference between a hot potato and a flying pig?////One\'s a heated yam, the other\'s a yeeted ham.','.NET developers are picky when it comes to food.////They only like chicken NuGet.']
def tell_joke(multiline="random"):
    if multiline=='random':
        x=random.randint(1,2)
        if x==1:
            y=random.randint(0,len(jokes1)-1)
            return jokes1[y]
        else:
            y=random.randint(0,len(jokes2)-1)
            return jokes2[y]
    elif multiline=='true' or multiline=='True' or multiline==0:
        y=random.randint(0,len(jokes2)-1)
        return jokes2[y]
    elif multiline=='false' or multiline=='False' or multiline==1:
        y=random.randint(0,len(jokes1)-1)
        return jokes1[y]

